version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: euro2024
      POSTGRES_DB: sgp
    expose:
    - "50432"
    ports:
      - "50432:50432"
    volumes:
      - sgp_data:/var/lib/postgresql/data
    command: -p 50432

volumes:
  sgp_data:
